default_platform(:ios)

platform :ios do
  desc "Fetch certificates and provisioning profiles"
  lane :certs do
    match(
      type: "appstore",
      readonly: true,
      app_identifier: [
        "com.#{ENV['TEAMID']}.loopkit.Loop"
      ]
    )
  end

  desc "Build the app for App Store"
  lane :build_loop do
    certs # Hent certs først
    build_app(
      scheme: "Loop",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.#{ENV['TEAMID']}.loopkit.Loop" => "match AppStore com.#{ENV['TEAMID']}.loopkit.Loop"
        }
      }
    )
  end
end

