name: Build Loop

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Loop
    runs-on: macos-latest

    env:
      TEAMID: ${{ secrets.TEAMID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby for fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install fastlane dependencies
        run: |
          gem install bundler
          bundle install

      - name: Fetch certificates using fastlane lane
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
          FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
          FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
          TEAMID: ${{ secrets.TEAMID }}
        run: |
          bundle exec fastlane certs
