name: Build Loop
on:
  workflow_dispatch:

jobs:
  build:
    name: Build Loop
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby for fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install fastlane dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Loop using fastlane
        run: bundle exec fastlane build
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          APP_STORE_CONNECT_API_KEY_PATH: ${{ secrets.APP_STORE_CONNECT_API_KEY_PATH }}
