name: 3. Create Certificates
run-name: Create Certificates (${{ github.ref_name }})

on:
  workflow_dispatch:

jobs:
  create-certs:
    name: Create Certificates
    runs-on: macos-13

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install Fastlane
        run: gem install fastlane

      - name: Debug Fastlane Path
        run: |
          echo "Fastlane gem directory:"
          ruby -e 'puts Gem::Specification.find_by_name("fastlane").gem_dir' || echo "Fastlane not found"

      - name: Patch Match Tables
        run: |
          TABLE_PRINTER_PATH=$(ruby -e 'puts Gem::Specification.find_by_name("fastlane").gem_dir')/match/lib/match/table_printer.rb
          if gem list fastlane -i > /dev/null && [ -f "$TABLE_PRINTER_PATH" ]; then
            sed -i '' "/puts(Terminal::Table.new(params))/d" "$TABLE_PRINTER_PATH"
          else
            echo "⚠️ Warning: table_printer.rb not found at $TABLE_PRINTER_PATH"
            echo "Skipping patch. This is usually not critical."
          fi

      - name: Install Bundler
        run: gem install bundler

      - name: Install Dependencies
        run: bundle install

      - name: Unlock macOS Keychain
        run: |
          security create-keychain -p "" actions.keychain
          security set-keychain-settings -t 3600 -u actions.keychain
          security list-keychains -s actions.keychain
          security unlock-keychain -p "" actions.keychain

      - name: Sync System Clock
        run: sudo sntp -sS time.windows.com

      - name: Run Fastlane to Check and Renew Certificates
        run: bundle exec fastlane check_and_renew_certificates
        env:
          TEAMID: ${{ secrets.TEAMID }}
          GH_PAT: ${{ secrets.GH_PAT }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
          FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
          FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
          FASTLANE_USERNAME: ${{ secrets.FASTLANE_USERNAME }}
          GITHUB_WORKSPACE: ${{ github.workspace }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
